version: "3.7"
services:
    csvserver:
       image: infracloudio/csvserver:latest
       ports:
        - 9393:9300
       volumes:
        - /root/inputFile:/csvserver/inputdata
       environment:
         CSVSERVER_BORDER: orange
